#!/usr/bin/env ruby

# Adapted from https://github.com/Gee-Bee/dotfiles.git

require 'fileutils'
require 'pathname'

# Recursively link files from source to target directory
def linkify source_path, target_path
  Dir.glob( File.join(source_path, '*'), File::FNM_DOTMATCH ).each do |src_fn_path|
    src_pn = Pathname.new src_fn_path
    next if %w(. ..).include? src_pn.basename.to_s
    if src_pn.directory?
      puts "mkdir -p #{File.join(target_path, src_pn.basename)}\n"
      FileUtils.mkdir_p File.join(target_path, src_pn.basename)
      linkify File.join(source_path, src_pn.basename), File.join(target_path, src_pn.basename)
    else
      puts "ln -s #{src_pn} #{File.join(target_path, src_pn.basename)}\n"
      FileUtils.ln_s src_pn, File.join(target_path, src_pn.basename), force: true
    end
  end
end

linkify File.join( File.expand_path(File.dirname(__FILE__)), 'symlinked' ), ENV['HOME']
