# GITIT, personal wiki with a git backend
# - auto start/stop on desktop events
# - manual via 'start/stop/status gitit'
# - $$ is the PID of the gitit job
author "hertogp"
description "gitit personal wiki server with git backend"
# console log to -> ~/.cache/upstart/gitit.log
console none
start on desktop-start
stop on desktop-stop

#pre-start script
#  echo "`date +%Y-%m-%d,%H:%M%:S` starting gitit"
#end script
#
#pre-stop script
#  echo "`date +%Y-%m-%d,%H:%M%:S` stoppint gitit"
#end script

script
  chdir /home/www/gitit
  # Exit 1 if we're already running (seems not needed)
  # status $UPSTART_JOB | grep -q running
  exec /home/pdh/.cabal/bin/gitit -f /home/www/gitit/.config +RTS -IO -RTS
end script
